services:
  postgres:
    image: postgres:15
    container_name: interbanking-db
    restart: always
    environment:
      POSTGRES_DB: interbanking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"