spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/interbanking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  springdoc:
    enable: true
    api-docs:
      enabled: true
      path: /api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
      operations-sorter: method
      tags-sorter: alpha
      disable-swagger-default-url: true
    enable-native-support: true